### ISSUE TITLE
Uncaught Error: Access to undeclared static property: TelegramBotPHP\Config\MainConfig::$logDatabase

### ISSUE THREAD

**Issue by Mo-0hammed** [ErfanBahramali/Telegram-Bot-PHP#2]
```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: TelegramBotPHP\Config\MainConfig::$logDatabase in /vendor/bahramali/telegram-bot-php/src/Config/Config.php:106
Stack trace:
#0 /vendor/bahramali/telegram-bot-php/src/Bot.php(45): TelegramBotPHP\Config\Config->__construct()
#1 /index.php(9): TelegramBotPHP\Bot->__construct()
#2 {main}
  thrown in /vendor/bahramali/telegram-bot-php/src/Config/Config.php on line 106

Fatal error: Uncaught Error: Access to undeclared static property: TelegramBotPHP\Config\MainConfig::$logDatabase in /vendor/bahramali/telegram-bot-php/src/Config/Config.php:106
Stack trace:
#0 /vendor/bahramali/telegram-bot-php/src/Bot.php(45): TelegramBotPHP\Config\Config->__construct()
#1 /index.php(9): TelegramBotPHP\Bot->__construct()
#2 {main}
  thrown in /vendor/bahramali/telegram-bot-php/src/Config/Config.php on line 106
```

**Comment by Mo-0hammed** [comment]
edit line 59 in MainConfig 
to `public static string $logDatabase = '';`
